### PR TITLE
Add support for phinx v0.13

### PR DESCRIPTION
**Pull request by JoyceBabu**
I have added support for phinx v0.13 and added PHP 8.2 to the test suite.

### CODE REVIEW

**Comment by JoyceBabu** [comment]
The tests were passing on my fork. Looks like it failed due to some network error.

**Comment by odan** [comment]
Thanks for the PR. But there are code style changes which do not belong into this PR.

**Comment by JoyceBabu** [comment]
I added the commit since the test suite was failing without it

https://github.com/JoyceBabu/phinx-migrations-generator/actions/runs/3801030939/jobs/6465076282

**Comment by odan** [comment]
Yes, please remove the code style changes. I have already updates the cs rules to fix this.

**Comment by odan** [comment]
Thank you!

**Pull request merged**
