### PR TITLE
Feature/various changes

### PR DESCRIPTION
**Pull request by alex2005git**

### CODE REVIEW

**Comment by odan** [comment]
There are so many changes in this PR. This is hard to review. Could you please split it into multiple PR in the future?

**Comment by odan** [comment]
Hello @alex2005git I just cherry picked everything except the new feature "Add new option 'null_no_quotes'" which should be explained a little bit more. Can you please add some more details/description for this new feature and explain the reason behind it?

**Comment by alex2005git** [comment]
A different PR for a commit that changes < 5 lines of code, seems like a waste of time IMO.
It's not that hard to review, lets be honest, you open each commit in a new tab and see the changes...

For the null_no_quotes, I'm using mariadb 12 something, and it needs to have NULL values without quotes (migrations throw errors because of it), I guess mysql does not have this problem.

**Comment by odan** [comment]
As far a I know the in MariaDB and MySQL the `COLUMN_DEFAULT` is by **default** `NULL`.  Therefore, it is not necessary to map "NULL" to `NULL`. Just leave the field `COLUMN_DEFAULT` blank :-)

**Comment by alex2005git** [comment]
This is still an issue for me.
I cant leave the column default to blank, what if this changes in a future release of mysql/mariadb. I like my db to be explicitly set and not be whatever the db sets it to.

As it is right now, my migrations are like this 
`$table->addColumn('email', 'string', ['null' => true, 'default' => "NULL", 'limit' => 100, 'collation' => "utf8mb4_unicode_ci", 'encoding' => "utf8mb4", 'after' => 'iduser']);`
As you can see the default is set to the string `NULL` which is not acceptable.

This is not breaking code, it just adds an extra option, I dont see the harm of it, plus it fixes my issue with the null values.
Can you please reconsider adding this?

**Comment by odan** [comment]
What should happend if another User needs the string `"NULL"` as default value and has enabled the mapping from `"NULL"` to `null`? 

> Can you please reconsider adding this?

Yes, as soon as MySQL or MariaDB change their current behavior.

**Comment by alex2005git** [comment]
What is a more common use, `NULL` as null value or `"NULL"` as a string?
I have never seen that, and I dont think any DB system admin that respects himself would ever set "NULL" string value as the default value.

Well the same could be said about what if another user needs the value NULL as the default value?
You cant have it both ways, and NULL seems to me the right approach.

Well, someone that sets his default values to "NULL" shouldn't enable this option. Wouldn't you say so?
Are they using in one column NULL and in another "NULL", that seems a bit strange and not consistent database design, so they would need to choose one way or another.

Again, this is an **optional setting**, I dont think anyone would enable it without knowing what they are doing, or if they need it.

**Pull request closed without merging**
