### PR TITLE
Add support for geospatial data types

### PR DESCRIPTION
**Pull request by rasmusbe**
Phinx already supports them

### CODE REVIEW

**Comment by rasmusbe** [comment]
I'm not sure if https://github.com/odan/phinx-migrations-generator/pull/25/files#diff-034e6caa75cffba1fcbaa1d76b7af878R858 is even correct.

I'm thinking that the function maybe can be simplified by just mapping types that needs change and return the original column type for rest, I don't see any case where it should be surrounded by [  ]

**Comment by odan** [comment]
Hi @rasmusbe ! Thanks for the PR.

Yes, the `[]` are not perfect. I think all unknown column types should throw an Exception. For example:

```php
throw new RuntimeException(sprintf('Unknown column type: %s', $type));
```

You are welcome to create a PR for it.

**Comment by rasmusbe** [comment]
Maybe, but I'm thinking that since the column type is from the current database we might just accept it, and if Phinx don't support the type, it will be Phinx responsibility to either throw an exception or to build support for it.

**Comment by rasmusbe** [comment]
I made a PR of how I think it should work since I got the time to do it now, but if you still thinks an exception is needed I can change it

**Pull request merged**
